const GET_ALL_USER_INFO_REQUEST = 'user/GET_ALL_USER_INFO_REQUEST'
const GET_ALL_USER_INFO_SUCCESS = 'user/GET_ALL_USER_INFO_SUCCESS'
const GET_ALL_USER_INFO_FAILURE = 'user/GET_ALL_USER_INFO_FAILURE'
const GET_ALL_USER_INFO_READ = 'user/GET_ALL_USER_INFO_READ'

export {
    GET_ALL_USER_INFO_REQUEST,
    GET_ALL_USER_INFO_SUCCESS,
    GET_ALL_USER_INFO_FAILURE,
    GET_ALL_USER_INFO_READ
}